[package]
name = "hydroflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sealed = "0.3"
slotmap = "1.0"
tuple_list = "0.1"
