[package]
name = "raw-proposer-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.14", features = [ "derive" ] }
rand = "0.8.4"
serde = { version = "1", features = [ "derive" ] }
bincode = "1.3"

[workspace]
